---
- name: Deploy Flask app
  hosts: webservers
  become: true
  remote_user: root
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
  
    - name: Install necessary packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python3-venv
          - git
        state: present
  
    - name: Create virtual environment
      command: python3 -m venv /opt/project2/env
  
    - name: Activate virtual environment
      command: /bin/bash -c "source /opt/project2/env/bin/activate"
  
    - name: Copy Flask app files
      copy:
        src: app.py
        dest: /opt/project2/app.py
  
    - name: Install flask using pip
      pip:
        name: flask
        executable: /opt/project2/env/bin/pip
        state: present

    - name: Allow incoming traffic on port 5000
      ufw:
        rule: allow
        proto: tcp
        port: 5000
        comment: "Allow incoming traffic to Flask app"
  
    - name: Restart UFW
      systemd:
        name: ufw
        state: restarted
  
    - name: Start Flask app
      command: /bin/bash -c "source /opt/project2/env/bin/activate && export FLASK_APP=/opt/project2/app.py && /opt/project2/env/bin/flask run --host=0.0.0.0 &"
      async: 0
      poll: 0 
...
