---
- name: Deploy Flask App
  hosts: webservers
  become: yes

  tasks:
    - name: Add the default Ubuntu repository
      apt_repository:
        repo: 'deb http://archive.ubuntu.com/ubuntu focal main'
        state: present

    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - git
          - nginx
          - gunicorn3

    - name: Create the destination folder
      file:
        path: /opt/flask-app
        state: directory
        mode: 0755

    - name: Clone the repository
      git:
        repo: https://github.com/johy9/flaskapp.git
        dest: /opt/flask-app
     
    - name: Install Flask and its dependencies
      pip:
        name: flask
        chdir: /opt/flask-app

    - name: Start the Flask App 
      command: python3 /opt/flask-app/app.py
      async: 1
      poll: 0
      register: flask_app_start_result

    - name: Debug the output
      debug:
        var: flask_app_start_result


    # - name: Start the Flask App
    #   command: python3 /opt/flask-app/app.py  
    #   args:
    #     creates: /var/run/flask-app.pid

    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/flask_app
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
...        
